[build]
  command = "pnpm run generate"
  publish = "dist/"

[[redirects]]
  from = "/bee.php"
  to = "https://cdn.splitbee.io/sb.js"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/_hive/*"
  to = "https://hive.splitbee.io/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}