[build]
  command = "yarn build"
  publish = ".output/"

[build.environment]
  NETLIFY_USE_YARN = "true"
  NODE_VERSION = "16.13.1"

[[redirects]]
  from = "/bee.php"
  to = "https://cdn.splitbee.io/sb.js"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/_hive/*"
  to = "https://hive.splitbee.io/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}