[build]
  base = "projects/zigzag-components/"
  command = "build-storybook"
  publish = "projects/zigzag-components/storybook-static/"

[context.production]
  environment = { NODE_VERSION = "16.13.0" }
