var projects_base = {
    pulsar_one: {
        name: 'Pulsar one [ø]',
        id: 'pulsar_one',
        tags: ['game'],
        preview: 'src/img/pulsar_one.jpg',
        gallery: ['src/img/pulsar_one.jpg'],
        tools: ['javascript', 'css3'],
        description: 'change your destiny',
        url: 'projects/pulsar_one',
        role: 'Lead developer',
        partners: ['Suong Kévin Tan : Leader/UI designer/Front-end developer',
            'Jennyfer Millet : Architect of the information/Game designer ',
            'Aymeric Chappuis : Sound & game designer ',
            'Aude Ficheux - Javascript developer (mini-games)',
        ],
        duration: '> 2 month',
        links: {
            0: {
                name: 'Github',
                href: 'https://github.com/AudeFi/Pulsar_one',
            },
        },
        year: 2016,
        case_study: {
            summary: 'Pulsar one is a game where the story evolve depending of your choices, you are the choosen who have to save the world.',
            context: 'This was a trimester challenge by team of 5/6 with my school, my favorite. The only instruction was "remake a game from the 80\'s", we picked the game ZORK ',
            process: 'The first step of this project was to write the story with all the team (1 week). After that we where more independant on each task : Kévin made the mocks of the UI and code the animations,  that I integrate into the core game. Aude coded 1 mini-game a week, Jennyfer had to translate written scenario into usable datas and Aymeric made a curated selection of musics and songs to set the game to another level',
            problems: 'The main issue was delays, the project was much bigger than it looked, also we made the game in full Javascript, no php so we had to manage user save and progression with broswer cookies wich is not pratical at all. Pulsar 2 is coming for the end of 2016 and it will be build with PHP to avoid this problem.',
            conclusion: 'We got 17.3/20 the best grade in the class',
        },
    },
    climbing_to_the_moon: {
        name: 'Climbing to the moon',
        id: 'climbing_to_the_moon',
        tags: ['game', 'teamwork'],
        preview: 'src/img/climbing_to_the_moon.jpg',
        gallery: [
            'src/img/focus_gallery/climbing_to_the_moon_0.jpg',
            'src/img/focus_gallery/climbing_to_the_moon_1.jpg',
            'src/img/focus_gallery/climbing_to_the_moon_2.jpg',
        ],
        banner: 'https://mir-s3-cdn-cf.behance.net/project_modules/hd/8c2a3425455291.563458c81dc61.png',
        tools: ['Illustrator', 'Photoshop', 'jQuery'],
        description: 'maybe you\'ll fly',
        url: 'http://adrienzaganelli.com/projects/moon/',
        role: 'Integrator',
        partners: ['Léonard Dupuis : Designer', 'Tibault Fabre : Developer (game) '],
        duration: '1 week',
        links: {
            0: {
                name: 'Github',
                href: 'https://github.com/adrienZ/Climbing-to-the-moon',
            },
            1: {
                name: 'Behance',
                href: 'https://www.behance.net/gallery/25455291/Climbing-to-the-moon-Character-design',
            },
        },
        year: 2015,
        case_study: {
            summary: 'Climbing to the moon is the story of two dreamy children, Tom and Léa, who want to go on the moon. To do so, they will build a "tower" by adding several elements. This game, made in javascript, target children and have to entertain them by bringing fantasy and fun.',
            context: 'This was a one week challenge by team of 5/6 with my school, one my favorite. The only instruction was "make a game" ',
            process: 'Tibault made the core game and i made the rest. It was my first time using jQuery. The design included several people of the team, you can see details on the Behance\'s link.',
            problems: 'The main issue was to accord designer creativity and the other developer\'s exigence, as integrator i was the mediator',
            conclusion: 'We got 12.5/20, but i really enjoyed this.',
        },
    },
    easy_twitch: {
        name: 'Easy Twitch',
        id: 'easy_twitch',
        tags: ['webapp', 'json'],
        preview: 'src/img/easy_twitch.jpg',
        gallery: ['src/img/easy_twitch.jpg'],
        banner: 'https://unsplash.it/700/400?random',
        tools: ['Handlebars.js', 'Twitch'],
        description: 'twitch & chill',
        url: 'https://adrienz.github.io/freecodecamp-projects/4-easy-twitch/',
        role: 'creator & developer',
        partners: ['none'],
        duration: '> 1 month',
        links: {
            0: {
                name: 'Github',
                href: 'https://github.com/adrienZ/easy-twitch',
            },
        },
        year: 2015,
        case_study: {
            summary: 'Easy twitch is a webapp using Twitch.tv that allow you to track and watch you favorites streams registered in a list.',
            context: 'This is a personal project coming from a problem of mine : it was a pain to switch between my favorites channels, and it allowed me to learn how to use an api.',
            process: 'I made everything, from the code to design, on my free time, i had to learn how browser cookies works, also handlebars.js',
            problems: 'Bugs. I learned the hard way that compatibility matter for the UX, a new version is coming for 2016 to improve both UX and compatibility, but it works like a charm in firefox.',
            conclusion: 'I like what i\'ve done event if it looks incomplete, it does it job and i hope the v2 may find a little success',
        },
    },
    smash_brawl_go: {
        name: 'Smash Brawl Go',
        id: 'smash_brawl_go',
        tags: ['game', 'teamwork'],
        preview: 'src/img/smash_brawl_go.jpg',
        gallery: ['src/img/smash_brawl_go.jpg'],
        banner: 'https://unsplash.it/700/400?random',
        tools: ['Github', 'Photoshop', 'Fullsreen.js'],
        description: 'it\'s gonna hurt',
        url: 'http://adrienzaganelli.com/projects/smash-brawl-go/demo.html',
        role: 'developer',
        partners: ['Louis Rialland : developer (game)', 'Corentin Marzin : developer', 'Emmanuel Naïm (illustrator)', 'Raphaël Zerbib (design)'],
        duration: '> 2 month',
        links: {
            0: {
                name: 'Github',
                href: 'https://github.com/adrienZ/jeu-de-go',
            },
        },
        year: 2015,
        case_study: {
            summary: 'Super Smash Brawl go, is a adaptation of the ancestral go game for the web. The main focus of this project was to modernize it and bring more fun to this board game',
            context: 'This was a trimestrial project by team of 5/6 with my school. We had a lot of good time and still work with a part of the team. The subject was at least to code the go game, all extra features were welcome.',
            process: 'We were 3 average coders, but we put all our energy in the code to make something great. Each time we made a feature we pushed on Github so someone can debug or update his files. I made the home page with fullscreen.js, the selection screen and the ui of the game.',
            problems: 'The code is god damn illisble. We did not know how to use well Github and work with local files sometimes, The browser cookies we used only work on firefox, finally, the site arborescence is complex because we finished the project in a hurry.',
            conclusion: 'We got 14.5/20, teamwork can do great think that i thought was impossible for us.',
        },
    },
    hermes_redesign: {
        name: 'Hermes Redesign',
        id: 'hermes_redesign',
        tags: ['UX/UI', 'e-commerce'],
        preview: 'https://upload.wikimedia.org/wikipedia/fr/4/41/Hermes-international.png',
        gallery: ['src/img/hermes_redesign.jpg'],
        banner: 'https://unsplash.it/700/400?random',
        tools: ['Sketch3', 'Invision'],
        description: 'Let\'s do some design',
        url: 'http://adrienzaganelli.com/projects/hermes/',
        role: 'Lead UX designer + prototype',
        partners: ['Pierre-Brice Haurie : UI designer', 'Louis-Victor Morgaut : Lead UI designer', 'Julien Girardeau : UX designer', 'Camille ALVAREZ DE JESUS : Boss'],
        duration: '1 week',
        links: {
            0: {
                name: 'none',
                href: '#',
            },
        },
        year: 2015,
        case_study: {
            summary: 'Redesign of Hermès Website ',
            context: 'This was a one week challenge by team of 5/6 with my school, one week of design. We had to redesign the Hermès e-commerce website.',
            process: 'The colored pages on the prototype have been made by the UI designers, the pages on black & white are whireframes that i\'ve made during the week, all the team used Sketch 3 for design, the protoype is made with Invision app.',
            problems: 'The main issues was to manage time, we only had one week and were 4 designers synchronisation was necessary',
            conclusion: 'I\'m still wainting fot the grade',
        },
    },
    star_wars_explorer: {
        name: 'Star Wars Explorer',
        id: 'star_wars_explorer',
        tags: ['map', '3D'],
        preview: 'src/img/star_wars_explorer.jpg',
        gallery: ['src/img/star_wars_explorer.jpg'],
        tools: ['Three.js', 'Photoshop', 'Swapi'],
        description: 'Hyperdrive jump !',
        url: 'http://adrienzaganelli.com/projects/star-wars/',
        role: 'developer',
        partners: ['Maëlle Gaonach (developer)', 'Mélisandre Pozo (design)', 'Galla Pillot (design)'],
        duration: '1 week',
        links: {
            0: {
                name: 'Github',
                href: 'https://github.com/adrienZ/star-wars-hetic-p2019',
            },
        },
        year: 2015,
        case_study: {
            summary: 'Star wars explorer is an interactive map that allow you to visit each planet of the Star Wars universe and display the main events from the movies.',
            context: 'This was a one week challenge by team of 5/6 with my school. The only instruction was "Star Wars" ',
            process: 'We use a lot of JSON : swapi api and ours. The first json is for the coordinates of the planets to make the map, the second one bring the planet data (diameter, population, ...) and the last one had the event by planet. Once we have all the data we use templating with Handlebars.js',
            problems: 'The first problem was the lack of developers in the team. Initially, we wanted to make the whole map in 3D with three.js, but we weren\'t good enought at canvas, we took a canvas from codepen to make the stars a then just put images in divs. At least the planet is rotating in 3D when you click on it.',
            conclusion: 'We got 10.5/20, we didn\t plan this project enought and lack of time, i call that learn the hard way !.',
        },
    },
    weather_app: {
        name: 'Weather App',
        id: 'weather_app',
        tags: ['geolocation', 'maps'],
        preview: 'src/img/weather_app.jpg',
        gallery: ['src/img/weather_app.jpg'],
        banner: 'https://unsplash.it/700/400?random',
        tools: ['Openweathermap.org', 'Bootstrap'],
        description: 'take your umbrella',
        url: 'http://s.codepen.io/adri_zag/debug/zvqNWE',
        role: 'developer & designer',
        partners: ['none'],
        duration: '< 2 days',
        links: {
            0: {
                name: 'Github',
                href: 'https://github.com/adrienZ/Weather-app',
            },
        },
        year: 2015,
        case_study: {
            summary: 'this is a webapp using Openweathermap.org\'s api that give your local weather',
            context: 'This is a personal project coming from Freecodecamp\'s ziplines',
            process: 'I made everything, both code and design, on my free time, i had to learn how geolocation work',
            problems: 'the api\'s key change often so i had to update my code or the webapp won\'t work',
            conclusion: 'I did not focus on the design but this small project was very instructive.',
        },
    },
    lichtenstein_portrait: {
        name: 'Lichtenstein Portrait',
        id: 'lichtenstein_portrait',
        tags: ['art', 'design'],
        preview: 'src/img/lichtenstein_portrait.jpg',
        gallery: ['src/img/lichtenstein_portrait.jpg'],
        banner: 'https://unsplash.it/700/400?random',
        tools: ['illustrator'],
        description: 'some pop-art',
        url: 'http://adrienzaganelli.com/projects/lichtenstein_portrait_hd.png',
        role: 'author',
        partners: ['none'],
        duration: '> 10 hours',
        links: {
            0: {
                name: 'none',
                href: '#',
            },
        },
        year: 2015,
        case_study: {
            summary: 'This is an self-portrait in Roy Lichtenstein\'s style',
            context: 'This was an Illustrator exercise in my first year at Hétic',
            process: 'I reproduced a picture',
            problems: 'none',
            conclusion: 'I\'ve got 17/20 and i\'m happy with it',
        },
    },
    market_me: {
        name: 'Market-ME.fr',
        id: 'market_me',
        tags: ['e-commerce', 'real-word project'],
        preview: 'src/img/market_me.jpg',
        gallery: [
            'src/img/market_me.jpg',
            'src/img/marketme_layout.jpg',
            'src/img/marketme_graph.jpg',
        ],

        banner: 'https://unsplash.it/700/400?random',
        tools: ['CodeIgniter', 'PHP', 'jQuery', 'highcharts.js'],
        description: 'pixel perfect',
        url: 'https://www.market-me.fr/',
        role: 'Front & Back end developer',
        partners: ['Barthélemy Chalvet', 'Léonard Chalvet', 'Alexandre Autret'],
        duration: '> 2 months',
        links: {
            0: {
                name: 'dribbble',
                href: 'https://dribbble.com/MarketMe',
            },
        },
        year: 2016,
        case_study: {
            summary: 'The Marketplace for Premium Design Resources. UI Kits, Icons, Presentations, Wordpress Theme & much more...',
            context: 'This was an Illustrator exercise in my first year at Hétic',
            process: 'I reproduced a picture',
            problems: 'none',
            conclusion: 'I\'ve got 17/20 and i\'m happy with it',
        },
    },
    wiki_view: {
        name: 'Wikipedia Viewer',
        id: 'wiki_view',
        tags: ['search engine', 'api', 'freecodecamp'],
        preview: 'src/img/wiki_view.jpg',
        gallery: [
            'src/img/wiki_view.jpg',
        ],

        banner: 'https://unsplash.it/700/400?random',
        tools: ['Javascript', 'jQuery', 'Wikipedia API'],
        description: 'pixel perfect',
        url: 'http://s.codepen.io/adri_zag/debug/PzEvLE',
        role: 'Maker (all)',
        partners: ['none'],
        duration: '< 1 day',
        links: {
        },
        year: 2016,
        case_study: {
            summary: 'The Marketplace for Premium Design Resources. UI Kits, Icons, Presentations, Wordpress Theme & much more...',
            context: 'This was an Illustrator exercise in my first year at Hétic',
            process: 'I reproduced a picture',
            problems: 'none',
            conclusion: 'I\'ve got 17/20 and i\'m happy with it',
        },
    },
    kung_fury: {
        name: 'Kung Fury poster',
        tags: ['Illustrator', 'movie', 'illusration'],
        url: 'https://www.behance.net/gallery/35494931/Kung-Fury-Poster-Inspiration-by-Olly-Moss',
        role: 'Maker (all)',
        year: 2016,
    },
    moonchild: {
        name: 'Moonchild',
        tags: ['webRTC', 'tracking'],
        url: 'https://www.behance.net/gallery/35494931/Kung-Fury-Poster-Inspiration-by-Olly-Moss',
        role: 'Maker (all)',
        year: 2016,
    },
    airfrance: {
        name: 'airfrance',
        tags: ['invision', 'design', 'checkout'],
        url: 'http://adrienzaganelli.com/projects/airfrance/',
        role: 'Maker (all)',
        year: 2016,
    },
};


var projects = {
  'Free code camp' :
        [
          projects_base.wiki_view,
          projects_base.weather_app ,
          projects_base.easy_twitch,
        ],
  'School' :
        [
            projects_base.star_wars_explorer,
            projects_base.climbing_to_the_moon,
            projects_base.smash_brawl_go,
        ],
    'Design':
        [
          projects_base.airfrance,
          projects_base.kung_fury,
          projects_base.hermes_redesign,

        ],
}
