name: daily-umami-report

on:
  schedule:
    - cron: "30 17 * * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  umamiReport:
    name: umami report
    runs-on: ubuntu-latest

    steps:
      - name: Create Umami report
        id: umamiReport
        uses: boly38/action-umami-report@umami-server-2.9.0
        with:
          umami-server: https://${{secrets.UMAMI_HOST}}
          umami-user: ${{secrets.UMAMI_USERNAME}}
          umami-password: ${{secrets.UMAMI_PASSWORD}}
          umami-site-domain: ${{secrets.UMAMI_SITE_DOMAIN}}
          umami-report-file: "umamiReport.txt"
        env:
          UMAMI_CLIENT_TIMEOUT_MS: 5000
      - name: print var
        run: |
          echo yolo: ${{steps.umamiReportStep.outputs.umamiOneLineReport}}

      # - name: Send Umami report to discord channel
      #   uses: tsickert/discord-webhook@v4.0.0
      #   with:
      #     webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
      #     content: ${{ steps.umamiReportStep.outputs.umamiOneLineReport }}
      #     embed-title: "Umami report"
      #     username: "umami report"
      #     embed-description: "${{ steps.umamiReportStep.outputs.umamiReport }}"
      #     embed-image-url: "https://raw.githubusercontent.com/umami-software/umami/master/src/assets/logo.svg"
